# Generated by Django 2.2 on 2020-05-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
                ('type_scheme', models.CharField(choices=[('NFSA', 'NFSA'), ('APL', 'APL'), ('MDM', 'MDM'), ('PMGKY', 'PMGKY')], default='NFSA', max_length=20)),
                ('type_grain', models.CharField(choices=[('RICE', 'RICE'), ('WHEAT', 'WHEAT'), ('DAL', 'DAL')], default='RICE', max_length=20)),
                ('os', models.IntegerField(default=0)),
                ('uthan', models.IntegerField(default=0)),
                ('vitran', models.IntegerField(default=0)),
                ('agami', models.IntegerField(default=0)),
            ],
        ),
    ]
