# Generated by Django 2.2 on 2020-06-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0006_category_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='product_id',
            field=models.IntegerField(default=1),
        ),
    ]
