# Generated by Django 2.2 on 2020-06-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0007_addproduct_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_cart', models.CharField(max_length=2000)),
            ],
        ),
    ]
