# Generated by Django 2.2 on 2020-06-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0008_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
                ('value_cart', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
