# Generated by Django 2.2 on 2020-06-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0009_auto_20200619_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='placeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('contact', models.IntegerField(blank=True, unique=True)),
                ('add', models.CharField(max_length=250)),
                ('item', models.CharField(max_length=20)),
                ('value_cart', models.CharField(max_length=2000)),
            ],
        ),
    ]
