# Generated by Django 2.2 on 2020-06-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0011_auto_20200620_0827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoryi',
        ),
    ]
