# Generated by Django 2.2 on 2020-06-20 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0012_auto_20200620_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.IntegerField(default=1)),
                ('cat_name', models.CharField(max_length=50)),
                ('cover_pic', models.FileField(upload_to='media')),
                ('description', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondapp.Category'),
        ),
        migrations.DeleteModel(
            name='Categoryi',
        ),
    ]
